/* ------------------------------------------------------------------ */
/*  Employee Portal – Route Configuration                              */
/*  Migrated from Routes/allRoutes.js                                  */
/* ------------------------------------------------------------------ */

import type { AppRoute } from "@craft-apex/auth";

/* ------------------------------------------------------------------ */
/*  Public Routes (no auth required)                                   */
/* ------------------------------------------------------------------ */
export const publicRoutes: AppRoute[] = [
  { path: "/login", title: "Login", section: "auth", requiresAuth: false },
  { path: "/logout", title: "Logout", section: "auth", requiresAuth: false },
  { path: "/forgot-password", title: "Forgot Password", section: "auth", requiresAuth: false },
  { path: "/reset-password/[id]", title: "Reset Password", section: "auth", requiresAuth: false },
  { path: "/default/route", title: "Default Route", section: "auth", requiresAuth: false },
];

/* ------------------------------------------------------------------ */
/*  Auth-Protected Routes                                              */
/* ------------------------------------------------------------------ */
export const protectedRoutes: AppRoute[] = [
  // ─── Dashboard ────────────────────────────────────────────────────
  { path: "/dashboard", title: "Dashboard", section: "dashboard", requiresAuth: true },
  { path: "/summary", title: "Summary", section: "dashboard", requiresAuth: true },

  // ─── Lead Management ─────────────────────────────────────────────
  { path: "/lead/list", title: "Lead List", section: "leads", requiresAuth: true },
  { path: "/lead/create", title: "Create Lead", section: "leads", requiresAuth: true },
  { path: "/lead/create/[id]", title: "Edit Lead", section: "leads", requiresAuth: true },
  { path: "/lead/dedupe-q", title: "Dedupe Queue", section: "leads", requiresAuth: true },
  { path: "/lead/transfer", title: "Lead Transfer", section: "leads", requiresAuth: true },
  { path: "/lead/list/login-q", title: "Login Queue", section: "leads", requiresAuth: true },
  { path: "/lead/list/tracking-q", title: "Tracking Queue", section: "leads", requiresAuth: true },
  { path: "/lead/list/disbursed-q", title: "Disbursed Queue", section: "leads", requiresAuth: true },
  { path: "/lead/list/rejected-q", title: "Rejected Queue", section: "leads", requiresAuth: true },
  { path: "/lead/list/approval-q", title: "Approval Queue", section: "leads", requiresAuth: true },
  { path: "/lead/list/fulfilled", title: "Fulfilled Leads", section: "leads", requiresAuth: true },
  { path: "/lead/list/archived", title: "Archived Leads", section: "leads", requiresAuth: true },
  { path: "/lead/lender-view", title: "Lender View", section: "leads", requiresAuth: true },
  { path: "/lead/bulk-upload", title: "Lead Bulk Upload", section: "leads", requiresAuth: true },
  { path: "/fulfillment/list", title: "Fulfillment List", section: "leads", requiresAuth: true },
  { path: "/check-bureau/lead/list", title: "Check Bureau", section: "leads", requiresAuth: true },

  // ─── Enquiry Management ───────────────────────────────────────────
  { path: "/enquiry/lead/list", title: "Enquiry Lead List", section: "enquiry", requiresAuth: true },
  { path: "/enquiry/customer/list", title: "Customer Enquiry", section: "enquiry", requiresAuth: true },
  { path: "/enquiry/customer/lead", title: "Customer Lead", section: "enquiry", requiresAuth: true },
  { path: "/enquiry/customer/lead/[id]", title: "Customer Lead Detail", section: "enquiry", requiresAuth: true },
  { path: "/enquiry/bulk-upload", title: "Enquiry Bulk Upload", section: "enquiry", requiresAuth: true },

  // ─── LOS (Loan Origination System) ───────────────────────────────
  { path: "/los/login-initiate", title: "LOS Login Initiate", section: "los", requiresAuth: true },
  { path: "/los/login-initiate/[id]", title: "LOS Login Detail", section: "los", requiresAuth: true },
  { path: "/los/login-q", title: "Login Queue", section: "los", requiresAuth: true },
  { path: "/los/login-view", title: "Login View", section: "los", requiresAuth: true },
  { path: "/los/appraisal-q", title: "Appraisal Queue", section: "los", requiresAuth: true },
  { path: "/los/appraisal-view", title: "Appraisal View", section: "los", requiresAuth: true },
  { path: "/los/underwriting-q", title: "Underwriting Queue", section: "los", requiresAuth: true },
  { path: "/los/underwriting-view", title: "Underwriting View", section: "los", requiresAuth: true },
  { path: "/los/acceptance-q", title: "Acceptance Queue", section: "los", requiresAuth: true },
  { path: "/los/acceptance-view", title: "Acceptance View", section: "los", requiresAuth: true },
  { path: "/los/appeal-q", title: "Appeal Queue", section: "los", requiresAuth: true },
  { path: "/los/appeal-view", title: "Appeal View", section: "los", requiresAuth: true },

  // ─── Operations / Verification ────────────────────────────────────
  { path: "/operations/verification", title: "Verification", section: "operations", requiresAuth: true },
  { path: "/operations/verification/[id]", title: "Verification Detail", section: "operations", requiresAuth: true },
  { path: "/operations/verification/list", title: "Verification List", section: "operations", requiresAuth: true },
  { path: "/operations/verification/summary", title: "Verification Summary", section: "operations", requiresAuth: true },
  { path: "/operations/verification/task/list", title: "Verification Tasks", section: "operations", requiresAuth: true },
  { path: "/operations/verification/transfer", title: "Verification Transfer", section: "operations", requiresAuth: true },

  // ─── Partner Management ───────────────────────────────────────────
  { path: "/partner/onboarding", title: "Partner Onboarding", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/[id]", title: "Partner Detail", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/in-progress", title: "Partner In Progress", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/pending", title: "Partner Pending", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/approved", title: "Partner Approved", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/approved/[id]", title: "Approved Partner Detail", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/rejected", title: "Partner Rejected", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/archived", title: "Partner Archived", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/inactive", title: "Partner Inactive", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/child-partner", title: "Child Partners", section: "partner", requiresAuth: true },
  { path: "/partner/onboarding/child-partner/approval", title: "Child Partner Approval", section: "partner", requiresAuth: true },
  { path: "/partner/renewal/[id]", title: "Partner Renewal", section: "partner", requiresAuth: true },
  { path: "/partner/renewal/list/[Status]", title: "Partner Renewals List", section: "partner", requiresAuth: true },
  { path: "/partner/user/list", title: "Partner Users", section: "partner", requiresAuth: true },
  { path: "/partner/bulk-upload", title: "Partner Bulk Upload", section: "partner", requiresAuth: true },
  { path: "/partner/impersonate", title: "Impersonate Partner", section: "partner", requiresAuth: true },
  { path: "/partner-view", title: "Partner View", section: "partner", requiresAuth: true },

  // ─── Vendor Management ────────────────────────────────────────────
  { path: "/vendor/onboarding", title: "Vendor Onboarding", section: "vendor", requiresAuth: true },
  { path: "/vendor/onboarding/[id]", title: "Vendor Detail", section: "vendor", requiresAuth: true },
  { path: "/vendor/onboarding/in-progress", title: "Vendor In Progress", section: "vendor", requiresAuth: true },
  { path: "/vendor/onboarding/pending", title: "Vendor Pending", section: "vendor", requiresAuth: true },
  { path: "/vendor/onboarding/rejected", title: "Vendor Rejected", section: "vendor", requiresAuth: true },
  { path: "/vendor/onboarding/approved", title: "Vendor Approved", section: "vendor", requiresAuth: true },
  { path: "/vendor/onboarding/approved/[id]", title: "Vendor Approved Detail", section: "vendor", requiresAuth: true },

  // ─── APF Management ───────────────────────────────────────────────
  { path: "/apf/onboarding", title: "APF Onboarding", section: "apf", requiresAuth: true },
  { path: "/apf/onboarding/[id]", title: "APF Detail", section: "apf", requiresAuth: true },
  { path: "/apf/onboarding/in-progress", title: "APF In Progress", section: "apf", requiresAuth: true },
  { path: "/apf/onboarding/pending", title: "APF Pending", section: "apf", requiresAuth: true },
  { path: "/apf/onboarding/rejected", title: "APF Rejected", section: "apf", requiresAuth: true },
  { path: "/apf/onboarding/approved", title: "APF Approved", section: "apf", requiresAuth: true },
  { path: "/apf/onboarding/approved/[id]", title: "APF Approved Detail", section: "apf", requiresAuth: true },

  // ─── Collections ──────────────────────────────────────────────────
  { path: "/collection/field/add-recovery", title: "Add Recovery", section: "collection", requiresAuth: true },
  { path: "/collection/field/add-recovery/[id]", title: "Recovery Detail", section: "collection", requiresAuth: true },
  { path: "/collection/follow-up", title: "Collection Follow-up", section: "collection", requiresAuth: true },
  { path: "/collection/follow-up/[id]", title: "Follow-up Detail", section: "collection", requiresAuth: true },
  { path: "/collection/upload/list", title: "Upload Collections List", section: "collection", requiresAuth: true },
  { path: "/upload/collection", title: "Upload Collection", section: "collection", requiresAuth: true },
  { path: "/active/accounts", title: "Active Accounts", section: "collection", requiresAuth: true },
  { path: "/closed/accounts", title: "Closed Accounts", section: "collection", requiresAuth: true },
  { path: "/tele/collect/list-q", title: "Tele Collection Queue", section: "collection", requiresAuth: true },
  { path: "/tele/collect/list/view", title: "Tele Collection View", section: "collection", requiresAuth: true },
  { path: "/collection/field/collection-q", title: "Field Collection Queue", section: "collection", requiresAuth: true },
  { path: "/collection/field/collection-view", title: "Field Collection View", section: "collection", requiresAuth: true },
  { path: "/collection/summary", title: "Collection Summary", section: "collection", requiresAuth: true },
  { path: "/collection/ots-initiate", title: "OTS Initiate", section: "collection", requiresAuth: true },
  { path: "/collection/ots-initiate/[id]", title: "OTS Workflow", section: "collection", requiresAuth: true },
  { path: "/collection/repossession/[id]", title: "Repossession", section: "collection", requiresAuth: true },
  { path: "/collection/repossession/view", title: "Repossession View", section: "collection", requiresAuth: true },

  // ─── Loan Management (LMS) ────────────────────────────────────────
  { path: "/loan-management/view", title: "Loan Management", section: "lms", requiresAuth: true },
  { path: "/loan-management/repayment/[id]", title: "Repayment", section: "lms", requiresAuth: true },
  { path: "/loan-management/repayment-new/[id]", title: "Repayment New", section: "lms", requiresAuth: true },
  { path: "/loan-management/reschedule-request", title: "Reschedule Request", section: "lms", requiresAuth: true },
  { path: "/loan-management/reschedule-queue", title: "Reschedule Queue", section: "lms", requiresAuth: true },
  { path: "/loan-management/restructure-request", title: "Restructure Request", section: "lms", requiresAuth: true },
  { path: "/loan-management/restructure-queue", title: "Restructure Queue", section: "lms", requiresAuth: true },
  { path: "/loan-management/loan-account-statement", title: "Loan Account Statement", section: "lms", requiresAuth: true },
  { path: "/loan/account/create", title: "Create Loan Account", section: "lms", requiresAuth: true },
  { path: "/loan/account/create/[id]", title: "Edit Loan Account", section: "lms", requiresAuth: true },
  { path: "/loan/account/pending", title: "Pending Loans", section: "lms", requiresAuth: true },
  { path: "/loan/account/upload", title: "Upload Loan Account", section: "lms", requiresAuth: true },
  { path: "/reschedule/simulate", title: "Reschedule Simulate", section: "lms", requiresAuth: true },
  { path: "/add-service-request", title: "Service Request", section: "lms", requiresAuth: true },
  { path: "/add-service-request/[id]", title: "Service Request Detail", section: "lms", requiresAuth: true },
  { path: "/service-request/queue", title: "Service Request Queue", section: "lms", requiresAuth: true },
  { path: "/add-reschedule", title: "Add Reschedule", section: "lms", requiresAuth: true },
  { path: "/add-reschedule/[id]", title: "Reschedule Detail", section: "lms", requiresAuth: true },
  { path: "/lms/bank-statement-reconciliation", title: "Bank Statement Reconciliation", section: "lms", requiresAuth: true },

  // ─── Disbursement ─────────────────────────────────────────────────
  { path: "/part-disbursement", title: "Part Disbursement", section: "disbursement", requiresAuth: true },
  { path: "/part-disbursement/flow", title: "Disbursement Flow", section: "disbursement", requiresAuth: true },
  { path: "/part-disbursement/flow/[id]", title: "Disbursement Detail", section: "disbursement", requiresAuth: true },
  { path: "/part-disbursement/flow/list", title: "Sanctioned Queue", section: "disbursement", requiresAuth: true },
  { path: "/disbursement/batch-process", title: "Disbursement Batch", section: "disbursement", requiresAuth: true },
  { path: "/beneficiary-credit", title: "Beneficiary Credit", section: "disbursement", requiresAuth: true },
  { path: "/new-beneficiary-credit", title: "New Beneficiary Credit", section: "disbursement", requiresAuth: true },

  // ─── Repayment ────────────────────────────────────────────────────
  { path: "/repayment/follow-up", title: "Repayment Follow-up", section: "repayment", requiresAuth: true },
  { path: "/repayment/follow-up/[id]", title: "Repayment Detail", section: "repayment", requiresAuth: true },

  // ─── Finance ──────────────────────────────────────────────────────
  { path: "/finance/payable-scheme-list", title: "Payable Schemes", section: "finance", requiresAuth: true },
  { path: "/finance/add-payable-scheme", title: "Add Payable Scheme", section: "finance", requiresAuth: true },
  { path: "/finance/add-payable-scheme/[id]", title: "Edit Payable Scheme", section: "finance", requiresAuth: true },
  { path: "/finance/receivable-scheme-list", title: "Receivable Schemes", section: "finance", requiresAuth: true },
  { path: "/finance/add-receivable-scheme", title: "Add Receivable Scheme", section: "finance", requiresAuth: true },
  { path: "/finance/add-receivable-scheme/[id]", title: "Edit Receivable Scheme", section: "finance", requiresAuth: true },
  { path: "/finance/receivable-estimate", title: "Receivable Estimate", section: "finance", requiresAuth: true },
  { path: "/finance/payable-estimate", title: "Payable Estimate", section: "finance", requiresAuth: true },
  { path: "/finance/receivable-invoice", title: "Receivable Invoice", section: "finance", requiresAuth: true },
  { path: "/finance/payable-invoice", title: "Payable Invoice", section: "finance", requiresAuth: true },
  { path: "/finance/invoice-details", title: "Invoice Details", section: "finance", requiresAuth: true },
  { path: "/finance/invoice-details/[id]", title: "Invoice Detail", section: "finance", requiresAuth: true },
  { path: "/finance/payout-plan-list", title: "Payout Plans", section: "finance", requiresAuth: true },
  { path: "/finance/add-payout-plan", title: "Add Payout Plan", section: "finance", requiresAuth: true },
  { path: "/finance/add-payout-plan/[id]", title: "Edit Payout Plan", section: "finance", requiresAuth: true },
  { path: "/finance/lender-payout-upload", title: "Payout Upload", section: "finance", requiresAuth: true },
  { path: "/finance/payout-reconciliation-view/[id]", title: "Payout Reconciliation", section: "finance", requiresAuth: true },
  { path: "/finance/adjustment-card", title: "Adjustments", section: "finance", requiresAuth: true },
  { path: "/finance/sales-performance/overview", title: "Sales Performance", section: "finance", requiresAuth: true },
  { path: "/finance/payment-processing", title: "Payment Processing", section: "finance", requiresAuth: true },
  { path: "/finance/payment-processing/add", title: "Add Payment", section: "finance", requiresAuth: true },
  { path: "/finance/batch-create", title: "Batch Create", section: "finance", requiresAuth: true },
  { path: "/finance/batch-create/[id]", title: "Batch Detail", section: "finance", requiresAuth: true },
  { path: "/finance/incentive-scheme-list", title: "Incentive Schemes", section: "finance", requiresAuth: true },
  { path: "/finance/add-incentive-scheme", title: "Add Incentive Scheme", section: "finance", requiresAuth: true },
  { path: "/finance/add-incentive-scheme/[id]", title: "Edit Incentive Scheme", section: "finance", requiresAuth: true },
  { path: "/finance/incentive-plan-list", title: "Incentive Plans", section: "finance", requiresAuth: true },
  { path: "/finance/add-incentive-plan", title: "Add Incentive Plan", section: "finance", requiresAuth: true },
  { path: "/finance/add-incentive-plan/[id]", title: "Edit Incentive Plan", section: "finance", requiresAuth: true },
  { path: "/finance/incentive-estimate-list", title: "Incentive Estimates", section: "finance", requiresAuth: true },
  { path: "/finance/sales-incentive/earnings", title: "Sales Incentive Earnings", section: "finance", requiresAuth: true },
  { path: "/finance/sales-payable/earnings", title: "Sales Payable Earnings", section: "finance", requiresAuth: true },
  { path: "/finance/incentive-statement", title: "Incentive Statement", section: "finance", requiresAuth: true },
  { path: "/finance/gst-status", title: "GST Status", section: "finance", requiresAuth: true },
  { path: "/finance/gst/vendor-gst", title: "Vendor GST", section: "finance", requiresAuth: true },
  { path: "/finance/gst/withheld", title: "GST Withheld", section: "finance", requiresAuth: true },
  { path: "/finance/gst/reversed-charge", title: "GST Reverse Charge", section: "finance", requiresAuth: true },
  { path: "/finance/gst/filing", title: "GST Filing", section: "finance", requiresAuth: true },
  { path: "/finance/tds/status", title: "TDS Status", section: "finance", requiresAuth: true },
  { path: "/finance/tds/filing", title: "TDS Filing", section: "finance", requiresAuth: true },
  { path: "/finance/payout-document", title: "Payout Document", section: "finance", requiresAuth: true },

  // ─── Finance / Accounting ─────────────────────────────────────────
  { path: "/finance/accounting/chart-of-accounts", title: "Chart of Accounts", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-charts-of-accounts", title: "Add Chart of Accounts", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-charts-of-accounts/[id]", title: "Edit Chart of Accounts", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/accounting-template", title: "Accounting Templates", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-accounting-template", title: "Add Template", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-accounting-template/[id]", title: "Edit Template", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/general-ledger", title: "General Ledger", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-general-ledger-entries", title: "Add GL Entry", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-general-ledger-entries/[id]", title: "Edit GL Entry", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/cost-center", title: "Cost Centers", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-cost-center", title: "Add Cost Center", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/add-cost-center/[id]", title: "Edit Cost Center", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/general-ledger-balance", title: "GL Balance", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/amort-view", title: "Amortisation", section: "accounting", requiresAuth: true },
  { path: "/finance/accounting/month-closing", title: "Month Closing", section: "accounting", requiresAuth: true },
  { path: "/finance/account/account-balance/list", title: "Account Balance", section: "accounting", requiresAuth: true },
  { path: "/finance/account/financials", title: "Financials", section: "accounting", requiresAuth: true },
  { path: "/finance/account/financials-new", title: "Financials New", section: "accounting", requiresAuth: true },
  { path: "/finance/company-details/bank-account", title: "Bank Account", section: "accounting", requiresAuth: true },

  // ─── Fixed Assets ─────────────────────────────────────────────────
  { path: "/finance/accounting/fixed-assets/dashboard", title: "Fixed Assets Dashboard", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/registration", title: "Asset Registration", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/registration/[id]", title: "Edit Asset", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/details/[code]", title: "Asset Details", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/transfer/[code]", title: "Asset Transfer", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/disposal/[code]", title: "Asset Disposal", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/capitalize/[code]", title: "Asset Capitalize", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/depreciation-run", title: "Depreciation Run", section: "fixed-assets", requiresAuth: true },
  { path: "/finance/accounting/fixed-assets/reports", title: "Asset Reports", section: "fixed-assets", requiresAuth: true },

  // ─── Treasury ─────────────────────────────────────────────────────
  { path: "/treasury/dashboard", title: "Treasury Dashboard", section: "treasury", requiresAuth: true },
  { path: "/treasury/alm", title: "ALM Dashboard", section: "treasury", requiresAuth: true },
  { path: "/liabilities/term-loan", title: "Term Loan", section: "treasury", requiresAuth: true },
  { path: "/surplus/fixed-deposit", title: "Fixed Deposit", section: "treasury", requiresAuth: true },
  { path: "/surplus/mutual-fund", title: "Mutual Fund", section: "treasury", requiresAuth: true },

  // ─── HR Management ────────────────────────────────────────────────
  { path: "/hr-mgmt/employee/salary-details/list", title: "Employee List", section: "hr", requiresAuth: true },
  { path: "/hr-mgmt/employee/salary-details", title: "Salary Details", section: "hr", requiresAuth: true },
  { path: "/hr-mgmt/leave-mgmt/leave-requests", title: "Leave Requests", section: "hr", requiresAuth: true },
  { path: "/hr-mgmt/payroll/batch-process", title: "Payroll Batch", section: "hr", requiresAuth: true },
  { path: "/hr-mgmt/payroll/batch-process/[id]", title: "Payroll Batch Detail", section: "hr", requiresAuth: true },
  { path: "/hr-mgmt/payroll/batch/list", title: "Payroll Batch List", section: "hr", requiresAuth: true },

  // ─── Reports ──────────────────────────────────────────────────────
  { path: "/reports/leads", title: "Lead Reports", section: "reports", requiresAuth: true },
  { path: "/reports/partners", title: "Partner Reports", section: "reports", requiresAuth: true },
  { path: "/reports/bank-analyser", title: "Bank Analyser", section: "reports", requiresAuth: true },
  { path: "/reports/bureau-analyser", title: "Bureau Analyser", section: "reports", requiresAuth: true },
  { path: "/reports/system-usage-report", title: "System Usage", section: "reports", requiresAuth: true },
  { path: "/reports/user-login-report", title: "User Login Report", section: "reports", requiresAuth: true },
  { path: "/reports/lead-journey", title: "Lead Journey", section: "reports", requiresAuth: true },
  { path: "/reports/bureau-reports-list", title: "Bureau Reports", section: "reports", requiresAuth: true },
  { path: "/reports/bureau-report-flow", title: "Bureau Report Flow", section: "reports", requiresAuth: true },
  { path: "/reports/bureau-report-flow/[id]", title: "Bureau Report Detail", section: "reports", requiresAuth: true },
  { path: "/reports/mis/process-status", title: "Process Status", section: "reports", requiresAuth: true },
  { path: "/reports/mis/bank-performance", title: "Bank Performance", section: "reports", requiresAuth: true },
  { path: "/reports/mis/source-productivity", title: "Source Productivity", section: "reports", requiresAuth: true },
  { path: "/reports/mis/product-performance", title: "Product Performance", section: "reports", requiresAuth: true },
  { path: "/reports/mis/month-wise-performance", title: "Month-wise Performance", section: "reports", requiresAuth: true },
  { path: "/reports/mis/pendency-reports", title: "Pendency Reports", section: "reports", requiresAuth: true },
  { path: "/reports/mis/channel-sales-reports", title: "Channel Sales", section: "reports", requiresAuth: true },
  { path: "/reports/mis/conveyance-report", title: "Conveyance Report", section: "reports", requiresAuth: true },
  { path: "/reports/mis/verification-tat-report", title: "Verification TAT", section: "reports", requiresAuth: true },
  { path: "/reports/mis/conveyance-distance-report", title: "Conveyance Distance", section: "reports", requiresAuth: true },
  { path: "/reports/mis/daily-sales-report", title: "Daily Sales", section: "reports", requiresAuth: true },
  { path: "/reports/mis/attendance-report", title: "Attendance Report", section: "reports", requiresAuth: true },
  { path: "/reports/mis/attendance-monthly-summary", title: "Attendance Summary", section: "reports", requiresAuth: true },
  { path: "/reports/mis/collection", title: "Collection Report", section: "reports", requiresAuth: true },
  { path: "/reports/lms/dashboard", title: "LMS Dashboard", section: "reports", requiresAuth: true },
  { path: "/reports/lms/collection-efficiency", title: "Collection Efficiency", section: "reports", requiresAuth: true },
  { path: "/reports/lms/dpd-aging", title: "DPD Aging", section: "reports", requiresAuth: true },
  { path: "/reports/lms/interest-accrual", title: "Interest Accrual", section: "reports", requiresAuth: true },
  { path: "/reports/lms/npa-movement", title: "NPA Movement", section: "reports", requiresAuth: true },
  { path: "/reports/lms/portfolio-overview", title: "Portfolio Overview", section: "reports", requiresAuth: true },

  // ─── Activity ─────────────────────────────────────────────────────
  { path: "/activity/live-tracking", title: "Live Tracking", section: "activity", requiresAuth: true },
  { path: "/activity/daily-activity", title: "Daily Activity", section: "activity", requiresAuth: true },
  { path: "/activity/lead-disposition", title: "Lead Disposition", section: "activity", requiresAuth: true },
  { path: "/activity/partner-disposition", title: "Partner Disposition", section: "activity", requiresAuth: true },
  { path: "/activity/overall-activity", title: "Overall Activity", section: "activity", requiresAuth: true },

  // ─── Marketing ────────────────────────────────────────────────────
  { path: "/marketing/campaign", title: "Campaigns", section: "marketing", requiresAuth: true },
  { path: "/marketing/campaign/create", title: "Create Campaign", section: "marketing", requiresAuth: true },
  { path: "/marketing/campaign/create/[id]", title: "Edit Campaign", section: "marketing", requiresAuth: true },
  { path: "/marketing/campaign/upload", title: "Campaign Upload", section: "marketing", requiresAuth: true },
  { path: "/marketing/campaign/upload/create", title: "Create Upload", section: "marketing", requiresAuth: true },
  { path: "/marketing/campaign/summary", title: "Campaign Summary", section: "marketing", requiresAuth: true },
  { path: "/marketing/campaign/[id]", title: "Audience List", section: "marketing", requiresAuth: true },
  { path: "/marketing/audience/create", title: "Create Audience", section: "marketing", requiresAuth: true },
  { path: "/marketing/audience/[id]", title: "Audience Detail", section: "marketing", requiresAuth: true },
  { path: "/marketing/link", title: "Links", section: "marketing", requiresAuth: true },
  { path: "/marketing/link/create", title: "Create Link", section: "marketing", requiresAuth: true },
  { path: "/marketing/link/create/[id]", title: "Edit Link", section: "marketing", requiresAuth: true },
  { path: "/marketing/media", title: "Media", section: "marketing", requiresAuth: true },
  { path: "/marketing/media/create", title: "Create Media", section: "marketing", requiresAuth: true },
  { path: "/marketing/media/create/[id]", title: "Edit Media", section: "marketing", requiresAuth: true },

  // ─── Legal ────────────────────────────────────────────────────────
  { path: "/legal/action-view", title: "Legal Action", section: "legal", requiresAuth: true },
  { path: "/legal/action-view/[id]", title: "Legal Approval", section: "legal", requiresAuth: true },
  { path: "/legal/approval-view", title: "Legal Approval View", section: "legal", requiresAuth: true },
  { path: "/legal/view", title: "Legal View", section: "legal", requiresAuth: true },
  { path: "/legal/workflow", title: "Legal Workflow", section: "legal", requiresAuth: true },
  { path: "/legal/workflow/[id]", title: "Legal Workflow Detail", section: "legal", requiresAuth: true },
  { path: "/legal/pre-notice-list", title: "Pre-Legal Notice", section: "legal", requiresAuth: true },
  { path: "/legal/pre-notice/[id]", title: "Pre-Legal Steps", section: "legal", requiresAuth: true },
  { path: "/legal/section-138-list", title: "Section 138", section: "legal", requiresAuth: true },
  { path: "/legal/lok-adalat-list", title: "Lok Adalat", section: "legal", requiresAuth: true },
  { path: "/legal/civil-list", title: "Civil Cases", section: "legal", requiresAuth: true },
  { path: "/legal/sarfaesi-list", title: "SARFAESI", section: "legal", requiresAuth: true },
  { path: "/legal/arbitration-list", title: "Arbitration", section: "legal", requiresAuth: true },

  // ─── Target & Performance ─────────────────────────────────────────
  { path: "/target/plan-list", title: "Target Plans", section: "target", requiresAuth: true },
  { path: "/target/add-plan", title: "Add Plan", section: "target", requiresAuth: true },
  { path: "/target/add-plan/[id]", title: "Edit Plan", section: "target", requiresAuth: true },
  { path: "/assign-target/list-view", title: "Assign Target List", section: "target", requiresAuth: true },
  { path: "/assign-target", title: "Assign Target", section: "target", requiresAuth: true },
  { path: "/track-performance", title: "Track Performance", section: "target", requiresAuth: true },
  { path: "/incentive/attached-employees/list", title: "Attached Employees", section: "target", requiresAuth: true },
  { path: "/assign-incentive", title: "Assign Incentive", section: "target", requiresAuth: true },
  { path: "/territory-target/list", title: "Territory Targets", section: "target", requiresAuth: true },
  { path: "/territory-target/create", title: "Create Territory Target", section: "target", requiresAuth: true },
  { path: "/territory-target/create/[id]", title: "Edit Territory Target", section: "target", requiresAuth: true },

  // ─── Beat Plan ────────────────────────────────────────────────────
  { path: "/beat-plan/list", title: "Beat Plans", section: "beat-plan", requiresAuth: true },
  { path: "/beat-plan/[id]", title: "Beat Plan Detail", section: "beat-plan", requiresAuth: true },
  { path: "/beat-actual/[id]", title: "Beat Actual", section: "beat-plan", requiresAuth: true },
  { path: "/beat-actual/view", title: "Beat Actual View", section: "beat-plan", requiresAuth: true },

  // ─── Settings ─────────────────────────────────────────────────────
  { path: "/settings/employee", title: "Employee Management", section: "settings", requiresAuth: true },
  { path: "/settings/add-employee", title: "Add Employee", section: "settings", requiresAuth: true },
  { path: "/settings/add-employee/[id]", title: "Edit Employee", section: "settings", requiresAuth: true },
  { path: "/settings/loan-types", title: "Loan Types", section: "settings", requiresAuth: true },
  { path: "/settings/add-loan-types", title: "Add Loan Type", section: "settings", requiresAuth: true },
  { path: "/settings/add-loan-types/[id]", title: "Edit Loan Type", section: "settings", requiresAuth: true },
  { path: "/settings/lender", title: "Lender List", section: "settings", requiresAuth: true },
  { path: "/settings/add-lender", title: "Add Lender", section: "settings", requiresAuth: true },
  { path: "/settings/add-lender/[id]", title: "Edit Lender", section: "settings", requiresAuth: true },
  { path: "/settings/scheme-list", title: "Scheme List", section: "settings", requiresAuth: true },
  { path: "/settings/add-scheme", title: "Add Scheme", section: "settings", requiresAuth: true },
  { path: "/settings/add-scheme/[id]", title: "Edit Scheme", section: "settings", requiresAuth: true },
  { path: "/settings/territory-management", title: "Territory Management", section: "settings", requiresAuth: true },
  { path: "/settings/add-territory", title: "Add Territory", section: "settings", requiresAuth: true },
  { path: "/settings/add-territory/[id]", title: "Edit Territory", section: "settings", requiresAuth: true },
  { path: "/settings/workflow", title: "Workflows", section: "settings", requiresAuth: true },
  { path: "/settings/workflow/create", title: "Create Workflow", section: "settings", requiresAuth: true },
  { path: "/settings/workflow/create/[id]", title: "Edit Workflow", section: "settings", requiresAuth: true },
  { path: "/settings/workflow/component", title: "Workflow Components", section: "settings", requiresAuth: true },
  { path: "/settings/lookup-list", title: "Lookup List", section: "settings", requiresAuth: true },
  { path: "/settings/lookup-master/create", title: "Create Lookup", section: "settings", requiresAuth: true },
  { path: "/settings/template/list", title: "Templates", section: "settings", requiresAuth: true },
  { path: "/settings/template/create", title: "Create Template", section: "settings", requiresAuth: true },
  { path: "/settings/template/create/[id]", title: "Edit Template", section: "settings", requiresAuth: true },
  { path: "/settings/templates", title: "Config Templates", section: "settings", requiresAuth: true },
  { path: "/settings/document/checklist", title: "Document Checklist", section: "settings", requiresAuth: true },
  { path: "/settings/document/checklist/create", title: "Create Checklist", section: "settings", requiresAuth: true },
  { path: "/settings/document/checklist/create/[id]", title: "Edit Checklist", section: "settings", requiresAuth: true },
  { path: "/settings/verification/list", title: "Verification Types", section: "settings", requiresAuth: true },
  { path: "/settings/verification/add-verification-type", title: "Add Verification", section: "settings", requiresAuth: true },
  { path: "/settings/verification/add-verification-type/[id]", title: "Edit Verification", section: "settings", requiresAuth: true },
  { path: "/settings/cam-configuration/list", title: "CAM Configuration", section: "settings", requiresAuth: true },
  { path: "/settings/cam-configuration/create", title: "Create CAM", section: "settings", requiresAuth: true },
  { path: "/settings/cam-configuration/create/[id]", title: "Edit CAM", section: "settings", requiresAuth: true },
  { path: "/settings/rule/list", title: "Rules", section: "settings", requiresAuth: true },
  { path: "/settings/rule/create", title: "Create Rule", section: "settings", requiresAuth: true },
  { path: "/settings/rule/create/[id]", title: "Edit Rule", section: "settings", requiresAuth: true },
  { path: "/settings/apply-rule/list", title: "Apply Rules", section: "settings", requiresAuth: true },
  { path: "/settings/apply-rule/create", title: "Create Apply Rule", section: "settings", requiresAuth: true },
  { path: "/settings/apply-rule/create/[id]", title: "Edit Apply Rule", section: "settings", requiresAuth: true },
  { path: "/settings/parameter/list", title: "Parameters", section: "settings", requiresAuth: true },
  { path: "/settings/parameter/create", title: "Create Parameter", section: "settings", requiresAuth: true },
  { path: "/settings/parameter/create/[id]", title: "Edit Parameter", section: "settings", requiresAuth: true },
  { path: "/settings/role", title: "Roles", section: "settings", requiresAuth: true },
  { path: "/settings/role/create", title: "Create Role", section: "settings", requiresAuth: true },
  { path: "/settings/role/create/[id]", title: "Edit Role", section: "settings", requiresAuth: true },
  { path: "/settings/module/list", title: "Modules", section: "settings", requiresAuth: true },
  { path: "/settings/module/create", title: "Create Module", section: "settings", requiresAuth: true },
  { path: "/settings/module/create/[id]", title: "Edit Module", section: "settings", requiresAuth: true },
  { path: "/settings/provider-list", title: "Providers", section: "settings", requiresAuth: true },
  { path: "/settings/employer/list", title: "Employers", section: "settings", requiresAuth: true },
  { path: "/settings/employer/review/[id]", title: "Employer Review", section: "settings", requiresAuth: true },
  { path: "/settings/employer/upload", title: "Employer Upload", section: "settings", requiresAuth: true },
  { path: "/settings/employer/upload/create", title: "Upload Create", section: "settings", requiresAuth: true },
  { path: "/settings/map-list", title: "Map List", section: "settings", requiresAuth: true },
  { path: "/settings/lender/pin-code/list", title: "Pin Code List", section: "settings", requiresAuth: true },
  { path: "/settings/lender/pin-code/create", title: "Pin Code Create", section: "settings", requiresAuth: true },
  { path: "/settings/lender/eligible-pincode/list", title: "Eligible Pincodes", section: "settings", requiresAuth: true },
  { path: "/settings/company-gst", title: "Company GST", section: "settings", requiresAuth: true },
  { path: "/settings/delegation-matrix", title: "Delegation Matrix", section: "settings", requiresAuth: true },
  { path: "/settings/delegation-matrix/[id]", title: "Edit Delegation", section: "settings", requiresAuth: true },
  { path: "/settings/delegation-list", title: "Delegation List", section: "settings", requiresAuth: true },
  { path: "/settings/vehicle", title: "Vehicles", section: "settings", requiresAuth: true },
  { path: "/settings/scoring-engine", title: "Scoring Engine", section: "settings", requiresAuth: true },
  { path: "/settings/scoring-engine/add", title: "Add Scoring Engine", section: "settings", requiresAuth: true },
  { path: "/settings/scoring-engine/[id]", title: "Edit Scoring Engine", section: "settings", requiresAuth: true },
  { path: "/settings/journey-type/list", title: "Journey Types", section: "settings", requiresAuth: true },
  { path: "/settings/journey-type/list/create", title: "Create Journey Type", section: "settings", requiresAuth: true },
  { path: "/settings/journey-type/list/create/[id]", title: "Edit Journey Type", section: "settings", requiresAuth: true },
  { path: "/settings/builders", title: "Builders", section: "settings", requiresAuth: true },
  { path: "/settings/builders/create", title: "Create Builder", section: "settings", requiresAuth: true },
  { path: "/settings/builders/create/[id]", title: "Edit Builder", section: "settings", requiresAuth: true },
  { path: "/settings/npa-rules-list", title: "NPA Rules", section: "settings", requiresAuth: true },
  { path: "/settings/create-npa-rule", title: "Create NPA Rule", section: "settings", requiresAuth: true },
  { path: "/settings/npa-rule/[id]", title: "Edit NPA Rule", section: "settings", requiresAuth: true },
  { path: "/settings/portfolio-rule-master", title: "Portfolio Rules", section: "settings", requiresAuth: true },
  { path: "/settings/trade-advance", title: "Trade Advance", section: "settings", requiresAuth: true },
  { path: "/settings/trade-advance/list", title: "Trade Advance List", section: "settings", requiresAuth: true },
  { path: "/settings/trade-advance-tracker", title: "Trade Tracker", section: "settings", requiresAuth: true },
  { path: "/settings/used-vehicle-makes", title: "Vehicle Makes", section: "settings", requiresAuth: true },
  { path: "/settings/vehicle-models", title: "Vehicle Models", section: "settings", requiresAuth: true },
  { path: "/settings/vehicle-price-matrix", title: "Price Matrix", section: "settings", requiresAuth: true },
  { path: "/settings/new-vehicle-price", title: "New Vehicle Price", section: "settings", requiresAuth: true },

  // ─── Utility ──────────────────────────────────────────────────────
  { path: "/utility/pincode-eligibility", title: "Pincode Eligibility", section: "utility", requiresAuth: true },
  { path: "/utility/lead-reassign", title: "Lead Reassign", section: "utility", requiresAuth: true },
  { path: "/utility/business-card", title: "Business Card", section: "utility", requiresAuth: true },
  { path: "/utility/doc-checklist-share", title: "Checklist Share", section: "utility", requiresAuth: true },

  // ─── Profile ──────────────────────────────────────────────────────
  { path: "/profile", title: "User Profile", section: "profile", requiresAuth: true },
  { path: "/change-password", title: "Change Password", section: "profile", requiresAuth: true },
  { path: "/shareable-links", title: "Shareable Links", section: "profile", requiresAuth: true },
  { path: "/customer360-relationship", title: "Customer 360", section: "profile", requiresAuth: true },
  { path: "/customer360-relationship/[id]", title: "Customer 360 Detail", section: "profile", requiresAuth: true },

  // ─── Form Builder ─────────────────────────────────────────────────
  { path: "/form-builder", title: "Form Builder", section: "form-builder", requiresAuth: true },
  { path: "/field-list", title: "Field List", section: "form-builder", requiresAuth: true },
  { path: "/component-list", title: "Component List", section: "form-builder", requiresAuth: true },
  { path: "/field/create", title: "Create Field", section: "form-builder", requiresAuth: true },
  { path: "/field/create/[id]", title: "Edit Field", section: "form-builder", requiresAuth: true },
  { path: "/component/create", title: "Create Component", section: "form-builder", requiresAuth: true },
  { path: "/component/create/[id]", title: "Edit Component", section: "form-builder", requiresAuth: true },

  // ─── BC Onboarding ────────────────────────────────────────────────
  { path: "/bc/onboarding", title: "BC Onboarding", section: "bc", requiresAuth: true },
  { path: "/bc/onboarding/[id]", title: "BC Onboarding Detail", section: "bc", requiresAuth: true },
  { path: "/bc/pending", title: "BC Pending", section: "bc", requiresAuth: true },
  { path: "/bc/portfolio/view", title: "BC Portfolio", section: "bc", requiresAuth: true },
  { path: "/attach/fldg", title: "FLDG List", section: "bc", requiresAuth: true },
  { path: "/attach/fldg/add", title: "Attach FLDG", section: "bc", requiresAuth: true },
  { path: "/attach/fldg/add/[id]", title: "FLDG Detail", section: "bc", requiresAuth: true },
  { path: "/attach/loan-account", title: "Loan Account List", section: "bc", requiresAuth: true },
  { path: "/attach/loan-account/add", title: "Attach Loan Account", section: "bc", requiresAuth: true },
  { path: "/attach/loan-account/add/[id]", title: "Loan Account Detail", section: "bc", requiresAuth: true },

  // ─── Purchase Order ───────────────────────────────────────────────
  { path: "/purchase/purchase-order-list", title: "Purchase Orders", section: "purchase", requiresAuth: true },
  { path: "/purchase/purchase-order-add", title: "Add Purchase Order", section: "purchase", requiresAuth: true },
  { path: "/purchase/customer-purchase-order", title: "Customer PO", section: "purchase", requiresAuth: true },
  { path: "/purchase/purchase-invoice-add", title: "Add Invoice", section: "purchase", requiresAuth: true },
  { path: "/purchase/purchase-invoice-list", title: "Invoice List", section: "purchase", requiresAuth: true },
  { path: "/purchase/purchase-requisition", title: "Requisition", section: "purchase", requiresAuth: true },

  // ─── Misc ─────────────────────────────────────────────────────────
  { path: "/cdn-file-manager", title: "CDN File Manager", section: "misc", requiresAuth: true },
  { path: "/cron/jobs", title: "Cron Jobs", section: "misc", requiresAuth: true },
  { path: "/verification/enach-setup", title: "eNACH Setup", section: "misc", requiresAuth: true },
];

/** All routes for the Employee Portal */
export const allRoutes = [...publicRoutes, ...protectedRoutes];
