import React from 'react';
import { DynamicIcon } from 'lucide-react/dynamic';

// Mapping from icon class names to Lucide icon names
const iconClassToLucideNameMap: Record<string, string> = {
  // Remix Icons (ri-*)
  'ri-file-list-3-line': 'file-text',
  'ri-user-2-line': 'users-round',
  'ri-key-2-fill': 'key',
  'ri-dashboard-line': 'home',
  'ri-user-line': 'user',
  'ri-settings-line': 'settings',
  'ri-home-line': 'home',
  'ri-folder-line': 'folder',
  'ri-mail-line': 'mail',
  'ri-phone-line': 'phone',
  'ri-calendar-line': 'calendar',
  'ri-search-line': 'search',
  'ri-add-line': 'plus',
  'ri-delete-line': 'trash-2',
  'ri-edit-line': 'edit',
  'ri-save-line': 'save',
  'ri-download-line': 'download',
  'ri-upload-line': 'upload',
  'ri-share-line': 'share',
  'ri-copy-line': 'copy',
  'ri-cut-line': 'scissors',
  'ri-paste-line': 'clipboard',
  'ri-undo-line': 'undo',
  'ri-redo-line': 'redo',
  'ri-refresh-line': 'refresh-cw',
  'ri-close-line': 'x',
  'ri-check-line': 'check',
  'ri-arrow-left-line': 'arrow-left',
  'ri-arrow-right-line': 'arrow-right',
  'ri-arrow-up-line': 'arrow-up',
  'ri-arrow-down-line': 'arrow-down',
  'ri-menu-line': 'menu',
  'ri-more-line': 'more-horizontal',
  'ri-eye-line': 'eye',
  'ri-eye-off-line': 'eye-off',
  'ri-lock-line': 'lock',
  'ri-heart-line': 'heart',
  'ri-star-line': 'star',
  'ri-bookmark-line': 'bookmark',
  'ri-flag-line': 'flag',
  'ri-tag-line': 'tag',
  'ri-link-line': 'link',
  'ri-image-line': 'image',
  'ri-video-line': 'video',
  'ri-file-line': 'file',
  'ri-folder-open-line': 'folder-open',
  'ri-archive-line': 'archive',
  'ri-database-line': 'database',
  'ri-cloud-line': 'cloud',
  'ri-wifi-line': 'wifi',
  'ri-bluetooth-line': 'bluetooth',
  'ri-battery-line': 'battery',
  'ri-volume-up-line': 'volume-2',
  'ri-volume-down-line': 'volume-1',
  'ri-volume-mute-line': 'volume-x',
  'ri-file-list-line': 'list',
  'ri-file-text-line': 'file-text',
  'ri-filter-line': 'filter',
  'ri-sort-line': 'arrow-up-down',
  'ri-subtract-line': 'minus',
  'ri-error-warning-line': 'alert-triangle',
  'ri-information-line': 'info',
  'ri-message-line': 'message-circle',
  'ri-building-line': 'building',
  'ri-bank-line': 'building-2',
  'ri-money-dollar-circle-line': 'dollar-sign',
  'ri-wallet-line': 'wallet',
  'ri-shopping-cart-line': 'shopping-cart',
  'ri-computer-line': 'monitor',
  'ri-smartphone-line': 'smartphone',
  'ri-server-line': 'server',
  'ri-shield-line': 'shield',
  'ri-camera-line': 'camera',
  'ri-mic-line': 'mic',
  'ri-play-line': 'play',
  'ri-pause-line': 'pause',
  'ri-car-line': 'car',
  'ri-plane-line': 'plane',
  'ri-train-line': 'train',
  'ri-ship-line': 'ship',
  'ri-bike-line': 'bike',
  'ri-bus-line': 'bus',
  'ri-sun-line': 'sun',
  'ri-moon-line': 'moon',
  'ri-tree-line': 'trees',
  'ri-flower-line': 'flower',
  'ri-leaf-line': 'leaf',
  'ri-tools-line': 'wrench',
  'ri-hammer-line': 'hammer',
  'ri-scissors-line': 'scissors',
  'ri-brush-line': 'brush',
  'ri-palette-line': 'palette',
  'ri-chevron-up-line': 'chevron-up',
  'ri-chevron-down-line': 'chevron-down',
  'ri-chevron-left-line': 'chevron-left',
  'ri-chevron-right-line': 'chevron-right',
  
  // Line Awesome Icons (las la-*)
  'las la-tachometer-alt': 'activity',
  'las la-dashboard': 'home',
  'las la-user': 'user',
  'las la-users': 'users',
  'las la-cog': 'settings',
  'las la-cogs': 'settings-2',
  'las la-home': 'home',
  'las la-folder': 'folder',
  'las la-file': 'file',
  'las la-envelope': 'mail',
  'las la-phone': 'phone',
  'las la-calendar': 'calendar',
  'las la-search': 'search',
  'las la-plus': 'plus',
  'las la-trash': 'trash-2',
  'las la-edit': 'edit',
  'las la-save': 'save',
  'las la-download': 'download',
  'las la-upload': 'upload',
  'las la-share': 'share',
  'las la-copy': 'copy',
  'las la-cut': 'scissors',
  'las la-paste': 'clipboard',
  'las la-undo': 'undo',
  'las la-redo': 'redo',
  'las la-refresh': 'refresh-cw',
  'las la-times': 'x',
  'las la-check': 'check',
  'las la-arrow-left': 'arrow-left',
  'las la-arrow-right': 'arrow-right',
  'las la-arrow-up': 'arrow-up',
  'las la-arrow-down': 'arrow-down',
  'las la-bars': 'menu',
  'las la-ellipsis-h': 'more-horizontal',
  'las la-eye': 'eye',
  'las la-eye-slash': 'eye-off',
  'las la-lock': 'lock',
  'las la-unlock': 'lock-open',
  'las la-heart': 'heart',
  'las la-star': 'star',
  'las la-bookmark': 'bookmark',
  'las la-flag': 'flag',
  'las la-tag': 'tag',
  'las la-link': 'link',
  'las la-external-link-alt': 'external-link',
  'las la-image': 'image',
  'las la-video': 'video',
  'las la-file-alt': 'file-text',
  'las la-folder-open': 'folder-open',
  'las la-archive': 'archive',
  'las la-database': 'database',
  'las la-cloud': 'cloud',
  'las la-wifi': 'wifi',
  'las la-bluetooth': 'bluetooth',
  'las la-battery-full': 'battery',
  'las la-volume-up': 'volume-2',
   'las la-volume-down': 'volume-1',
   'las la-volume-mute': 'volume-x',
  'las la-list': 'list',
  'las la-filter': 'filter',
  'las la-sort': 'arrow-up-down',
  'las la-minus': 'minus',
  'las la-exclamation-triangle': 'alert-triangle',
  'las la-info-circle': 'info',
  'las la-comment': 'message-circle',
  'las la-building': 'building',
  'las la-university': 'building-2',
  'las la-dollar-sign': 'dollar-sign',
  'las la-wallet': 'wallet',
  'las la-shopping-cart': 'shopping-cart',
  'las la-desktop': 'monitor',
  'las la-mobile': 'smartphone',
  'las la-server': 'server',
  'las la-shield-alt': 'shield',
  'las la-camera': 'camera',
  'las la-microphone': 'mic',
  'las la-play': 'play',
  'las la-pause': 'pause',
  'las la-car': 'car',
  'las la-plane': 'plane',
  'las la-train': 'train',
  'las la-ship': 'ship',
  'las la-bicycle': 'bike',
  'las la-bus': 'bus',
  'las la-sun': 'sun',
  'las la-moon': 'moon',
  'las la-tree': 'trees',
  'las la-seedling': 'flower',
  'las la-leaf': 'leaf',
  'las la-wrench': 'wrench',
  'las la-hammer': 'hammer',
  'las la-paint-brush': 'brush',
  'las la-palette': 'palette',
  'las la-chevron-up': 'chevron-up',
  'las la-chevron-down': 'chevron-down',
  'las la-chevron-left': 'chevron-left',
  'las la-chevron-right': 'chevron-right',
  'las la-music': 'music',
  'las la-headphones': 'headphones',
  'las la-gamepad': 'gamepad-2',
  'las la-trophy': 'trophy',
  'las la-gift': 'gift',
  'las la-bell': 'bell',
  'las la-clock': 'clock',
  'las la-stopwatch': 'timer',
  'las la-map': 'map',
  'las la-map-marker': 'map-pin',
  'las la-compass': 'compass',
  'las la-route': 'route',
  'las la-globe': 'globe',
  'las la-chart-bar': 'bar-chart-3',
  'las la-chart-pie': 'pie-chart',
  'las la-chart-line': 'trending-up',
  'las la-calculator': 'calculator',
  'las la-credit-card': 'credit-card',
  'las la-shopping-bag': 'shopping-bag',
  'las la-store': 'store',
  'las la-ticket-alt': 'ticket',
  'las la-award': 'award',
  'las la-medal': 'medal',
  'las la-crown': 'crown',
  'las la-gem': 'gem',
  'las la-fire': 'flame',
  'las la-snowflake': 'snowflake',
  'las la-cloud-rain': 'cloud-rain',
  'las la-cloud-snow': 'cloud-snow',
  'las la-bolt': 'zap',
  'las la-umbrella': 'umbrella',
  'las la-wind': 'wind',
  'las la-thermometer': 'thermometer',
  'las la-tint': 'droplets',
  'las la-mountain': 'mountain',
  'las la-apple-alt': 'apple',
  'las la-coffee': 'coffee',
  'las la-wine-glass': 'wine',
  'las la-beer': 'beer',
  'las la-utensils': 'utensils',
  'las la-cookie': 'cookie',
  'las la-birthday-cake': 'cake',
  'las la-pizza-slice': 'pizza',
  'las la-fish': 'fish',
  'las la-egg': 'egg',
  'las la-lightbulb': 'lightbulb',
  'las la-lamp': 'lamp',
  'las la-fan': 'fan',
  'las la-tshirt': 'shirt',
  'las la-glasses': 'glasses',
  'las la-backpack': 'backpack',
  'las la-baby': 'baby',
  'las la-industry': 'factory',
  'las la-warehouse': 'warehouse',
  'las la-hospital': 'hospital',
  'las la-school': 'school',
  'las la-book-open': 'book-open',
  'las la-theater-masks': 'theater',
  'las la-ambulance': 'ambulance',
  'las la-rocket': 'rocket',
  'las la-satellite': 'satellite',
  'las la-table': 'table',
  'las la-check-circle': 'check-circle',
  'las la-times-circle': 'x-circle',
  'las la-target': 'target',
  'las la-arrows-alt': 'move',
  'las la-expand': 'maximize',
  'las la-compress': 'minimize',
  'las la-search-plus': 'zoom-in',
  'las la-search-minus': 'zoom-out',
  'las la-hand-paper': 'hand',
  'las la-font': 'type',
  'las la-flask': 'test-tube',
  'las la-bug': 'bug',
  'las la-brain': 'brain',
  'las la-dumbbell': 'dumbbell',
  'las la-balance-scale': 'scale',
  'las la-circle': 'circle',
  'las la-key': 'key',
  'las la-check-square': 'check-square',
  'las la-dot-circle': 'radio',
  'las la-tachometer': 'gauge',
  'las la-unlock-alt': 'unlock',
   
   // Direct Lucide icon names (for backward compatibility and direct usage)
  'home': 'home',
  'user': 'user',
  'users': 'users',
  'users-round': 'users-round',
  'settings': 'settings',
  'settings-2': 'settings-2',
  'file-text': 'file-text',
  'folder': 'folder',
  'mail': 'mail',
  'phone': 'phone',
  'calendar': 'calendar',
  'search': 'search',
  'plus': 'plus',
  'trash-2': 'trash-2',
  'edit': 'edit',
  'save': 'save',
  'download': 'download',
  'upload': 'upload',
  'share': 'share',
  'copy': 'copy',
  'scissors': 'scissors',
  'clipboard': 'clipboard',
  'undo': 'undo',
  'redo': 'redo',
  'refresh-cw': 'refresh-cw',
  'x': 'x',
  'check': 'check',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  'arrow-down': 'arrow-down',
  'menu': 'menu',
  'more-horizontal': 'more-horizontal',
  'eye': 'eye',
  'eye-off': 'eye-off',
  'lock': 'lock',
  'heart': 'heart',
  'star': 'star',
  'bookmark': 'bookmark',
  'flag': 'flag',
  'tag': 'tag',
  'link': 'link',
  'image': 'image',
  'video': 'video',
  'file': 'file',
  'activity': 'activity',
  'building': 'building',
  'shield': 'shield',
  'database': 'database',
  'globe': 'globe',
  'bar-chart-3': 'bar-chart-3',
  'pie-chart': 'pie-chart',
  'trending-up': 'trending-up',
  'credit-card': 'credit-card',
  'dollar-sign': 'dollar-sign',
  'package': 'package',
  'truck': 'truck',
  'briefcase': 'briefcase',
  'help-circle': 'help-circle',
  'bell': 'bell',
  'key': 'key'
};

/**
 * Converts icon class names (Remix, Line Awesome) or direct Lucide names to Lucide icon names
 * @param iconClass - The icon class name (e.g., 'ri-home-line', 'las la-home', 'home', 'users-round')
 * @returns The corresponding Lucide icon name or the original input if not found
 */
export function convertIconToLucideName(iconClass: string): string {
  if (!iconClass) return 'help-circle'; // Default fallback icon
  
  // Clean the icon class and convert to lowercase
  const cleanedClass = iconClass.trim().toLowerCase();
  
  // Check if it's in our mapping
  const lucideIconName = iconClassToLucideNameMap[cleanedClass];
  
  // Return the mapped name or the original input (assuming it's already a valid Lucide name)
  return lucideIconName || cleanedClass;
}

/**
 * Creates a React component that renders a Lucide icon dynamically
 * @param iconClass - The icon class name or Lucide icon name
 * @param props - Additional props to pass to the DynamicIcon component
 * @returns A React component that renders the icon
 */
export function getIconComponent(iconClass: string, props: any = {}): React.ReactElement {
  const iconName = convertIconToLucideName(iconClass);
  
  return React.createElement(DynamicIcon, {
    name: iconName,
    size: 16,
    ...props
  });
}

/**
 * Legacy function for backward compatibility
 * @deprecated Use getIconComponent instead
 */
export function convertIconToLucide(iconClass: string): any {
  return getIconComponent(iconClass);
}

export default {
  convertIconToLucideName,
  getIconComponent,
  convertIconToLucide
};